platform: linux
image_resource:
  type: docker-image
  source: {repository: pivotalservices/bosh2-docker}
inputs:
- name: git-snort-boshrelease
- name: version
outputs:
- name: boshrelease-output
- name: github-release-info
run:
  path: ./git-snort-boshrelease/ci/tasks/create-bosh-release.sh
