---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 18fgsa/pulledpork

inputs:
- name: snort-boshrelease-git

outputs:
- name: pulledpork-output

run:
  path: snort-boshrelease-git/ci/tasks/pulledpork.sh
