---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli

inputs:
- name: pulledpork-output
- name: snort-boshrelease-git

outputs:
- name: snort-boshrelease-git-modified

run:
  path: pulledpork-output/ci/tasks/update-snort-conf.sh
