name: &name snort

releases:
- name: snort
  version: 1.0.0
  url: https://github.com/govau/snort-boshrelease/releases/download/v1.0.0/snort-1.0.0.tgz
  sha1: 414ef9ce60ea7cb373059bdfb81e5ac37bccf45f

instance_groups:
- name: snort
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
  jobs:
  - name: snort
    release: snort

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 3000-30000
  update_watch_time: 3000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
