name: &name snort

releases:
- name: snort
  version: 1.0.2
  url: https://github.com/govau/snort-boshrelease/releases/download/v1.0.2/snort-1.0.2.tgz
  sha1: 34e44d637556ba6c29e92733a6d66a1daa8ae545

instance_groups:
- name: snort
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
  jobs:
  - name: snort
    release: snort
  properties:
    snort:
      rules: []
update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 3000-30000
  update_watch_time: 3000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
