---
jobs:

- name: update-snort-boshrelease-rules
  plan:
  - get: timer
    trigger: true
  - get: snort-boshrelease-git
  - task: pulledpork
    file: snort-boshrelease-git/ci/tasks/pulledpork.yml
    params:
      OINKCODE: {{oinkcode}}
      SNORT_VERSION: {{snort-version}}
  - task: update-snort-conf
    file: snort-boshrelease-git/ci/tasks/update-snort-conf.yml
    params:
      S3_ACCESS_KEY_ID: {{s3-access-key-id}}
      S3_SECRET_ACCESS_KEY: {{s3-secret-access-key}}
  - aggregate:
    - put: snort-boshrelease-git
      params:
        rebase: true
        repository: snort-boshrelease-git-modified

resources:
- name: timer
  type: time
  source:
    interval: 1h

- name: snort-boshrelease-git
  type: git
  source:
    branch: {{snort-release-branch}}
    private_key: {{github-private-key}}
    uri: {{snort-release-uri}}
